name: Create e621, DBR, and DBRE6 merged tag lists and push to repo

on:
  workflow_dispatch: # for manual triggering
  schedule:
    - cron: "0 0 1 */2 *"

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # initialize and update the submodule
      - name: Initialize and update submodule
        run: |
          git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # execute the script and fill in defaults, reminder: is hardcoded so new/less options require change here too
      - name: Run Python script
        run: |
          printf "\n\n\n\n\n\n" | python dbr_e6_tag_processor.py

      # move CSV files to respective directories in the submodule
      - name: Move CSV files to submodule directories
        run: |
          # navigate to submodule directory
          cd dbr-e621-lists-archive

          # move CSV files by file name prefix
          mv ../DBR*.csv tag-lists/danbooru/
          mv ../E6*.csv tag-lists/e621/
          mv ../DBRE6*.csv tag-lists/danbooru_e621_combined/

      # try commit and push changes to the submodule
      - name: Commit and push changes to submodule
        run: |
          cd dbr-e621-lists-archive
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tag-lists/*.csv
          git commit -m "Add/Update CSV files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
