name: Create e621, DBR, and DBRE6 merged tag lists and push to repo

on:
  workflow_dispatch: # for manual triggering
  schedule:
    - cron: "0 0 1 */2 *"

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the base repo and submodule
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "true"
          TOKEN: ${{ secrets.GH_PAT }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Execute the script to generate the CSV files
      - name: Run Python script
        run: |
          printf "\n\n\n\n\n\n" | python dbr_e6_tag_processor.py

      # Create the folder structure and move the CSV files into submodule directories
      - name: Move CSV files into submodule directories
        run: |
          # Create necessary directories in the submodule
          mkdir -p dbr-e621-lists-archive/tag-lists/danbooru
          mkdir -p dbr-e621-lists-archive/tag-lists/e621
          mkdir -p dbr-e621-lists-archive/tag-lists/danbooru_e621_combined
          ls
          # Move the generated CSV files into the appropriate submodule directories
          mv DBR_*.csv dbr-e621-lists-archive/tag-lists/danbooru/
          mv E6_*.csv dbr-e621-lists-archive/tag-lists/e621/
          mv DBRE6_combi_tags_*.csv dbr-e621-lists-archive/tag-lists/danbooru_e621_combined/

      # Step to configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Navigate to the submodule directory
          cd dbr-e621-lists-archive
          
          git pull origin main --no-rebase --allow-unrelated-histories
          
          # Add the new files in the submodule
          git add tag-lists/danbooru/*
          git add tag-lists/e621/*
          git add tag-lists/danbooru_e621_combined/*
          
          # Commit the changes
          git commit -m "Update tag lists: DBR, E6, and DBRE6"
      
          # Push the changes to the submodule repository
          git push "https://${{ secrets.GH_PAT }}@github.com/DraconicDragon/dbr-e621-lists-archive.git" HEAD:main

      - name: Update submodule in the main repo
        run: |
          # Go back to the main repository root
          cd ../..
          
          # Update the submodule to the latest commit
          git submodule update --remote dbr-e621-lists-archive
          
          # Commit and push the submodule update
          git add dbr-e621-lists-archive
          git commit -m "Update submodule to latest commit"
          git push "https://${{ secrets.GH_PAT }}@github.com/DraconicDragon/danbooru-e621-tag-list-processor" HEAD:main
