name: Update Submodule with "Hello World"

on:
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        submodules: recursive # Ensure submodules are checked out

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Navigate to submodule and create "hello_world.txt"
      run: |
        cd dbr-e621-lists-archive
        echo "hello world" > hello_world.txt
        git add hello_world.txt
        git commit -m "Add hello_world.txt"

    - name: Push changes to submodule repository
      run: |
        cd dbr-e621-lists-archive
        git push origin main
